version: '3'

services:

  a:
    image: "node:9"
    volumes:
      - ./A:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    command: npm run start:docker

  b:
    image: "node:9"
    volumes:
      - ./B:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
     - "5000:5000"
    command: npm run start:docker

  client:
    image: "node:9-alpine"
    volumes:
      - ./client:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
     - "3000:3000"
    command: npm start

  redis_a:
    image: "redis:alpine"

  redis_b:
      image: "redis:alpine"
